Milestone 1: Mobile-capstone-project
ArthurGC/Web_Design_Course_Website pull request #1
Opened 2021-06-28 22:01 UTC by ArthurGC

![](https://img.shields.io/badge/Microverse-blueviolet)
# First Capstone Project | Mobile Version - Day 1
:beginner: In this first milestone I:

- [ ] Set up the repository and tools.
- [ ] Choose the topic for your website. (Web Development Course - Web Design Course)
- [ ] Choose images, text, icons, fonts. (I made my own images and icons. I used the fonts from the guideline provided by Microverse)
- [ ] Create the 2 pages for mobile. (Home and About pages)
- [ ] Deploy the project.

2021-06-28 23:05 UTC, Shaher-11 requested changes
#### Hello @ArthurGC,

### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:smiley::smiley:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [ ] Add the loom video link to the readme file.
- [ ] You should follow these [design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) guidelines, including: Colors, Typography: font face, size, and weight, Layout: composition and space between elements.
- [ ] Check the comments below:point_down:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

2021-06-28 23:05 UTC, Shaher-11 commented on about.html
> +            <h1 class="headline__title">Web Design for Everybody: Basics of Web Development and Coding</h1>
Kindly style the heading as the given design below
![right1](https://user-images.githubusercontent.com/58376020/123713189-24caab80-d874-11eb-98d9-bfa852550524.png)

2021-06-28 23:05 UTC, Shaher-11 commented on about.html
> +            </div>
decrease the width of the div as shown below
![right2](https://user-images.githubusercontent.com/58376020/123713321-6e1afb00-d874-11eb-91db-0f74d2d52298.png)

2021-06-28 23:05 UTC, Shaher-11 commented on about.html
> +        </section>
Reduce the size of the text here and the socila icons 

#### Original Design
![right3](https://user-images.githubusercontent.com/58376020/123713452-bd612b80-d874-11eb-8bf8-1984b6ed61cd.png)

2021-06-28 23:05 UTC, Shaher-11 commented on index.html
> +                    </div>
the image is not dispayed here
![wrong3](https://user-images.githubusercontent.com/58376020/123713672-32ccfc00-d875-11eb-84c8-c351630aaf0e.png)

2021-06-28 23:05 UTC, Shaher-11 commented on index.html
> +        <section class="presenter">
The section should be designed like the below screenshot and take advantage of css flex
![right4](https://user-images.githubusercontent.com/58376020/123713741-5c862300-d875-11eb-962f-dd56b336bcfd.png)

2021-06-28 23:05 UTC, Shaher-11 commented on index.html
> +        <section class="program">
This section should look like the screenshot below on the desktop
![right5](https://user-images.githubusercontent.com/58376020/123713847-93f4cf80-d875-11eb-910e-437ecfffeead.png)

2021-06-30 19:10 UTC, vichuge requested changes
# Required Changes ♻️ ♻️ ⚠️ ⚠️ 🚦 🚦 

Hi dear student, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![star_wars_almost_there](https://user-images.githubusercontent.com/20563252/121369354-644f4900-c901-11eb-9844-50c85d0f206b.gif)


## Aspects to improve ♻️
_Check the comments under the review._

- It looks like you could improve the size a little bit, why we don't try to make little these parts on your project.
- [ ] The `Offered by` and `footer` section needs to make size changes to be like the original design.
![image](https://user-images.githubusercontent.com/20563252/124017870-d66cf800-d9ac-11eb-9a0d-d5a0b948a423.png)

- [ ] This part is big as needed, please, fix this 😄
![image](https://user-images.githubusercontent.com/20563252/124017732-af162b00-d9ac-11eb-8d39-07ad729a9b76.png)

- Fix these two details and you'll be on the other side.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 5 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-30 23:13 UTC, sinansevgi approved these changes
# Approved :heavy_check_mark: 

Hi @ArthurGC , 

You did great work with making all the changes requested by previous TSEs.
Kudos for using SCSS :+1:

Your project is complete!  
Congratulations! 🎉

You can merge this pull request and continue with your journey :wave: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

[Optional]
- [ ] Top black part of the menu is missing on your project. Looks like previous TSEs missed this. This will not affect the status of your project but if you want to make your project complete you can add this part also.
![Screenshot 2021-07-01 at 02-19-59 CC Global Summit 2015](https://user-images.githubusercontent.com/1642014/124043218-43b37400-da13-11eb-9a4c-443b102cc10c.png)


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-30 23:15 UTC, merged